/** Markdown formatting for analyses and test plans. */

import type { PrAnalysis, TestCase, TestPlan } from "./types.js";

const RISK_EMOJI: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
};

export function formatCaseLine(tc: TestCase): string {
  return `- **${tc.id}** — ${tc.title} _(area: ${tc.area}; platforms: ${tc.platforms.join(", ")})_`;
}

export function formatCaseFull(tc: TestCase): string {
  const lines = [
    `### ${tc.id} — ${tc.title}`,
    `- **Priority**: ${tc.priority} | **Area**: ${tc.area} | **Platforms**: ${tc.platforms.join(", ")} | **Automation**: ${tc.automation ?? "manual"}`,
  ];
  if (tc.preconditions) lines.push(`- **Preconditions**: ${tc.preconditions}`);
  lines.push(`- **Steps**:`);
  tc.steps.forEach((s, i) => lines.push(`  ${i + 1}. ${s}`));
  lines.push(`- **Expected**: ${tc.expected.trim()}`);
  return lines.join("\n");
}

export function formatAnalysisMarkdown(analysis: PrAnalysis): string {
  const { pr, areas, risk } = analysis;
  const lines: string[] = [
    `# TestMCP PR Analysis — ${pr.owner}/${pr.repo}#${pr.number}`,
    "",
    `**${pr.title}** by @${pr.author} (\`${pr.head_branch}\` → \`${pr.base_branch}\`)${pr.draft ? " — DRAFT" : ""}`,
    "",
    `${RISK_EMOJI[risk.level]} **Risk: ${risk.level.toUpperCase()} (${risk.score}/100)** | Size: ${risk.size_category} | ${pr.changed_files_count} files, +${pr.additions}/-${pr.deletions}`,
    "",
    "## Risk factors",
    "",
    ...risk.factors.map((f) => `- ${f}`),
    "",
    "## Functional areas impacted",
    "",
  ];

  if (areas.length === 0) {
    lines.push("_No mapped areas matched. Consider extending mappings.yaml for this repo._");
  } else {
    for (const a of areas) {
      lines.push(
        `- **${a.area}** (${a.criticality}, confidence: ${a.confidence}) — ${a.description}`
      );
      if (a.matched_files.length)
        lines.push(`  - Files: ${a.matched_files.slice(0, 8).join(", ")}${a.matched_files.length > 8 ? ` (+${a.matched_files.length - 8} more)` : ""}`);
      if (a.matched_keywords.length)
        lines.push(`  - Keywords in title/body: ${a.matched_keywords.join(", ")}`);
    }
  }

  lines.push("", `Next step: call \`testmcp_generate_test_plan\` for the full prioritized plan.`);
  return lines.join("\n");
}

export function formatPlanMarkdown(plan: TestPlan, fullDetail: boolean): string {
  const { pr, risk, areas, matched_cases } = plan;
  const totalMatched =
    matched_cases.P0.length + matched_cases.P1.length + matched_cases.P2.length + matched_cases.P3.length;

  const lines: string[] = [
    `# 🧪 TestMCP Test Plan — ${pr.owner}/${pr.repo}#${pr.number}`,
    "",
    `**${pr.title}** by @${pr.author} | ${pr.url}`,
    "",
    `${RISK_EMOJI[risk.level]} **Risk: ${risk.level.toUpperCase()} (${risk.score}/100)** | Size: ${risk.size_category} | Areas hit: ${areas.map((a) => a.area).join(", ") || "none mapped"}`,
    "",
    `## Scope recommendation`,
    "",
    plan.regression_recommendation,
    "",
    `## Test cases (${totalMatched} matched)`,
  ];

  for (const priority of ["P0", "P1", "P2", "P3"] as const) {
    const cases = matched_cases[priority];
    if (!cases.length) continue;
    const label =
      priority === "P0"
        ? "P0 — Critical (must pass before release)"
        : priority === "P1"
          ? "P1 — High"
          : priority === "P2"
            ? "P2 — Medium"
            : "P3 — Low (time permitting)";
    lines.push("", `### ${label}`, "");
    for (const tc of cases) {
      lines.push(fullDetail ? formatCaseFull(tc) + "\n" : formatCaseLine(tc));
    }
  }

  if (plan.coverage_gaps.length) {
    lines.push("", "## ⚠️ Coverage gaps", "");
    lines.push(...plan.coverage_gaps.map((g) => `- ${g}`));
  }

  if (plan.suggested_new_case_prompts.length) {
    lines.push(
      "",
      "## 🤖 Suggested AI-generated additions",
      "",
      "_TestMCP matched the deterministic library above. Ask your agent to expand these prompts into net-new, PR-specific edge cases:_",
      ""
    );
    lines.push(...plan.suggested_new_case_prompts.map((p) => `- ${p}`));
  }

  lines.push("", `---`, `_Generated by TestMCP at ${plan.generated_at}_`);
  return lines.join("\n");
}
